added the partial seeder files. they need to be written in. fixed the error CS0104 'IdentityConstants' is an ambiguous reference between 'Cookbook.Common.GlobalConstants.IdentityConstants' and 'Microsoft.AspNetCore.Identity.IdentityConstants'  by aliasing to IdentityConstants in project commons Global constants